Presentation/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Presentation.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = ".id";

			return View();
		}

	}
}

Presentation/Controllers/ReportController.cs
using Data.ViewModel;
using Logic.Services.Report;
using Repository;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Controllers
{
	public class ReportController : Controller
	{
        private readonly ReportService service;

        public ReportController()
        {
            LGAContext context = new LGAContext();
            service = new ReportService(context);
        }

		// GET: Disadvs
		public ActionResult Index()
		{

			ViewData["States"] = service.States.Select(p => new SelectListItem()
			{
				Value = p.StateId.ToString(),
				Text = p.StateName,
				Selected = (p.StateName.Equals("Victoria", StringComparison.CurrentCultureIgnoreCase))
			})
			.ToList();

            var cached = System.Web.HttpContext.Current.Cache["ReportController:Index"] as IEnumerable<ReportModel>;
            if (cached == null)
            {
                cached = service.GetDisadges(null);
                System.Web.HttpContext.Current.Cache["ReportController:Index"] = cached;
            }
            return View(cached);
        }

		public ActionResult ReportGrid(string stateId, bool showAll = false)
		{
			int id = stateId != null ? int.Parse(stateId) : -1;

            var cached = System.Web.HttpContext.Current.Cache["ReportController:ReportGrid:"+ stateId + ":"+showAll] as IEnumerable<ReportModel>;
            if (cached == null)
            {
                cached = service.GetDisadges(id, showAll);
                System.Web.HttpContext.Current.Cache["ReportController:ReportGrid:" + stateId + ":" + showAll] = cached;
            }
            return PartialView(cached);
		}
	}
}

Presentation/Controllers/ScoresController.cs
using Data.ViewModel;
using Logic.Services.Report;
using Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Presentation.Controllers
{
	public class ScoresController : Controller
	{
        private ReportService service;

        public ScoresController()
        {
            LGAContext context = new LGAContext();
            service = new ReportService(context);
        }

		// GET: Scores
		public ActionResult Index()
		{
			ViewData["States"] = service.States.Select(p => new SelectListItem()
			{
				Value = p.StateId.ToString(),
				Text = p.StateName,
				Selected = (p.StateName.Equals("Victoria", StringComparison.CurrentCultureIgnoreCase))
			})
			.ToList();

			return View(service.GetAllData(null));
		}
		public ActionResult DataGrid(string stateId)
		{
			int id = stateId != null ? int.Parse(stateId) : -1;
			return PartialView(service.GetAllData(id));
		}
	}
}

Presentation/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>This is test project for .id</p>

Presentation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>.Id code challenge</h1>
    <p class="lead">This code challenge is a mandotory pre-step for us to invite you for the technical/design interview.</p>
    <p></p>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Problem solving</h2>
        <p> Fix at least couple of defects to display correct data.</p>
    </div>
    <div class="col-md-3">
        <h2>Quality</h2>
        <p>Think of a way to improve the code quality, then implement it. This could include implementing a unit or integration test</p>
    </div>
    <div class="col-md-3">
        <h2>Performance</h2>
        <p>Think and implement a different approach that you may improve the performance.</p>
    </div>
    <div class="col-md-3">
        <h2>Innovation</h2>
        <p>Think of any part you would rewrite it in a different  way and implement.</p>
    </div>
</div>

Presentation/Views/Report/Index.cshtml
@using Data.ViewModel;
@model IEnumerable<ReportModel>
@section Scripts
{
	<script>
    $(function(){
      $("#States_SelectedList").change(function (e) {
        var val = $(this).val();
        $("#reportPartial").load("/Report/ReportGrid?stateId=" + val);

        $("#showAll").text('Show All');
        $("#showAll").attr("href", "#showAll");
      });

      $("#showAll").click(function (e) {
        e.preventDefault();
        var state = $("#States_SelectedList option:selected").val();
        var val = $(this).attr("href");
        if (val === "#showAll") {
          $("#reportPartial").load("/Report/ReportGrid?showAll=true&stateId=" + state);
          $(this).text('Show Above Median');
          $(this).attr("href", "#aboveMedian");
        }
        if (val === "#aboveMedian") {
          $("#reportPartial").load("/Report/ReportGrid?showAll=false&stateId=" + state);
          $(this).text('Show All');
          $(this).attr("href", "#showAll");
        }
      });
    });
	</script>
}

@{
	ViewBag.Title = "Report";
}

<h2>Report</h2>

<div class="col-md-3"></div>
<div class="row col-md-6">
	@{
		List<SelectListItem> states = ViewData["States"] as List<SelectListItem>;
		string vicId = ViewData["VicId"] as string;
		}
	@Html.DropDownList("States_SelectedList", states)

  <a href="#showAll" id="showAll">Show All</a>
</div>
<div class="col-md-3"></div>
<br/><br/>
<div id="reportPartial">
	@Html.Partial("ReportGrid", Model)
</div>

Presentation/Views/Report/ReportGrid.cshtml
@using Data.ViewModel;
@model IEnumerable<ReportModel>

<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Disadvantage2011)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Disadvantage2016)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Comparison)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.PlaceName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.StateName)
		</th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Disadvantage2011)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Disadvantage2016)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Comparison)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.PlaceName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.StateName)
			</td>

		</tr>
	}

</table>

Presentation/Views/Scores/DataGrid.cshtml
@model IEnumerable<Data.ViewModel.DataModel>
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.StateName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.PlaceName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Year)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.DisadvantageScore)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.AdvantageDisadvantageScore)
		</th>

	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.StateName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.PlaceName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Year)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.DisadvantageScore)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.AdvantageDisadvantageScore)
			</td>
		</tr>
	}

</table>

Presentation/Views/Scores/Index.cshtml
@model IEnumerable<Data.ViewModel.DataModel>
@section Scripts
{
	<script>
		$(function () {
			$("#Data_SelectedList").change(function (e) {
				var val = $(this).val();
				$("#dataPartial").load("/Scores/DataGrid?stateId=" + val);
			});
		});
	</script>
}
@{
	ViewBag.Title = "All data";
}

<h2>All data by state</h2>
<div class="col-md-3"></div>
<div class="row col-md-6">
	@{
		List<SelectListItem> states = ViewData["States"] as List<SelectListItem>;
	}
	@Html.DropDownList("Data_SelectedList", states)
</div>
<div class="col-md-3"></div>
<br /><br />
<div id="dataPartial">
	@Html.Partial("DataGrid", Model)
</div>

Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - .id</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(".Id", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Home", "Index", "Home")</li>
					<li>@Html.ActionLink("Report", "Index", "Report")</li>
					<li>@Html.ActionLink("All Data", "Index", "Scores")</li>
					<li>@Html.ActionLink("About", "About", "Home")</li>

				</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - .Id</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>